# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
ignore_docker_version: false #enforce_docker_version: true in new release
nodes:
  - address: "rkeclusternode0.westeurope.cloudapp.azure.com"
    role:
    - controlplane
    - worker
    - etcd
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
  - address: "rkeclusternode1.westeurope.cloudapp.azure.com"
    role:
    - controlplane
    - worker
    - etcd
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
  - address: "rkeclusternode2.westeurope.cloudapp.azure.com"
    role:
    - controlplane
    - worker
    - etcd
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
  - address: "rkeclusternode3.westeurope.cloudapp.azure.com"
    role:
    - worker
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
  - address: "rkeclusternode4.westeurope.cloudapp.azure.com"
    role:
    - worker
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
  - address: "rkeclusternode5.westeurope.cloudapp.azure.com"
    role:
    - worker
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
  - address: "rkeclusternode6.westeurope.cloudapp.azure.com"
    role:
    - worker
    user: rke
    ssh_key_path: "./.ssh_keys/id_rsa"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3
  kube-api:
    image: rancher/k8s:v1.8.7-rancher1-1
  kube-controller:
    image: rancher/k8s:v1.8.7-rancher1-1
  scheduler:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}
  kubelet:
    image: rancher/k8s:v1.8.7-rancher1-1
  kubeproxy:
    image: rancher/k8s:v1.8.7-rancher1-1
    extra_args: {}

system_images:
  etcd: quay.io/coreos/etcd:v3.3
  kubernetes: rancher/k8s:v1.8.7-rancher1-1
  alpine: alpine:3.7
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  kubernetes_services_sidecar: rancher/rke-service-sidekick:v0.1.0
  kubedns: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0
